### ISSUE TITLE
Implement css to clojure map converter

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-fiddle#19]
it should be possible to paste css and get clojure map
```css
{
	width: 117px;
	height: 20px;
	font-family: SFUIText;
	font-size: 16px;
	line-height: 1.25;
	letter-spacing: -0.2px;
	text-align: left;
	color: #4360df;
}
```
to
```clojure
{
:width 117
:height 20
:font-family "SFUIText"
:font-size 16
:line-height 1.25
:letter-spacing -0.2
:text-align :left
:color "#4360df"
}
```
